// RUN: hlo-opt %s --platform=CUDA --stage=llvm-before-optimizations --xla_gpu_target_config_filename=${A100_CONFIG} | FileCheck --check-prefixes=CHECK,CHECK-%{PTX} %{IR_SUBST} %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL: entry:
// CHECK:         %[[VAL_0:.*]] = call i32 [[CTAIDX]]
// CHECK:         %[[VAL_1:.*]] = call i32 [[TIDX]]
// CHECK-PTX:     %[[VAL_2:.*]] = mul nuw nsw i32 %[[VAL_0]], 128
// CHECK-GCN:     %[[VAL_2:.*]] = mul nuw nsw i32 %[[VAL_0]], 256
// CHECK:         %[[VAL_3:.*]] = add nuw nsw i32 %[[VAL_2]], %[[VAL_1]]
// CHECK:         %[[VAL_4:.*]] = icmp ult i32 %[[VAL_3]], 11008
// CHECK:         call void @llvm.assume(i1 %[[VAL_4]])
// CHECK:         %[[VAL_5:.*]] = udiv i32 %[[VAL_3]], 1
// CHECK:         %[[VAL_6:.*]] = icmp ult i32 %[[VAL_3]], 11000
// CHECK:         br i1 %[[VAL_6]], label %[[VAL_7:.*]], label %[[VAL_8:.*]]
// CHECK:       fusion.in_bounds-after:                           ; preds = %[[VAL_9:.*]], %[[VAL_10:.*]]
// CHECK:         ret void
// CHECK:       fusion.in_bounds-true:                            ; preds = %[[VAL_10]]
// CHECK:         br label %[[VAL_11:.*]]
// CHECK:       concat_index_from_operand_id0:                    ; preds = %[[VAL_12:.*]]
// CHECK:         %[[VAL_13:.*]] = phi i32 [ 0, %[[VAL_12]] ]
// CHECK:         %[[VAL_14:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_13]]
// CHECK:         %[[VAL_15:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_16:.*]], i32 0, i32 %[[VAL_14]]
// CHECK:         %[[VAL_17:.*]] = load float, ptr %[[VAL_15]], align 4, !invariant.load
// CHECK:         %[[VAL_18:.*]] = fptrunc float %[[VAL_17]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id1:                    ; preds = %[[VAL_19:.*]]
// CHECK:         %[[VAL_20:.*]] = phi i32 [ 1000, %[[VAL_19]] ]
// CHECK:         %[[VAL_21:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_20]]
// CHECK:         %[[VAL_22:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_23:.*]], i32 0, i32 %[[VAL_21]]
// CHECK:         %[[VAL_24:.*]] = load float, ptr %[[VAL_22]], align 4, !invariant.load
// CHECK:         %[[VAL_25:.*]] = fptrunc float %[[VAL_24]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id2:                    ; preds = %[[VAL_26:.*]]
// CHECK:         %[[VAL_27:.*]] = phi i32 [ 2000, %[[VAL_26]] ]
// CHECK:         %[[VAL_28:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_27]]
// CHECK:         %[[VAL_29:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_30:.*]], i32 0, i32 %[[VAL_28]]
// CHECK:         %[[VAL_31:.*]] = load float, ptr %[[VAL_29]], align 4, !invariant.load
// CHECK:         %[[VAL_32:.*]] = fptrunc float %[[VAL_31]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id3:                    ; preds = %[[VAL_33:.*]]
// CHECK:         %[[VAL_34:.*]] = phi i32 [ 3000, %[[VAL_33]] ]
// CHECK:         %[[VAL_35:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_34]]
// CHECK:         %[[VAL_36:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_37:.*]], i32 0, i32 %[[VAL_35]]
// CHECK:         %[[VAL_38:.*]] = load float, ptr %[[VAL_36]], align 4, !invariant.load
// CHECK:         %[[VAL_39:.*]] = fptrunc float %[[VAL_38]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id4:                    ; preds = %[[VAL_40:.*]]
// CHECK:         %[[VAL_41:.*]] = phi i32 [ 4000, %[[VAL_40]] ]
// CHECK:         %[[VAL_42:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_41]]
// CHECK:         %[[VAL_43:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_44:.*]], i32 0, i32 %[[VAL_42]]
// CHECK:         %[[VAL_45:.*]] = load float, ptr %[[VAL_43]], align 4, !invariant.load
// CHECK:         %[[VAL_46:.*]] = fptrunc float %[[VAL_45]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id5:                    ; preds = %[[VAL_47:.*]]
// CHECK:         %[[VAL_48:.*]] = phi i32 [ 5000, %[[VAL_47]] ]
// CHECK:         %[[VAL_49:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_48]]
// CHECK:         %[[VAL_50:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_51:.*]], i32 0, i32 %[[VAL_49]]
// CHECK:         %[[VAL_52:.*]] = load float, ptr %[[VAL_50]], align 4, !invariant.load
// CHECK:         %[[VAL_53:.*]] = fptrunc float %[[VAL_52]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id6:                    ; preds = %[[VAL_54:.*]]
// CHECK:         %[[VAL_55:.*]] = phi i32 [ 6000, %[[VAL_54]] ]
// CHECK:         %[[VAL_56:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_55]]
// CHECK:         %[[VAL_57:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_58:.*]], i32 0, i32 %[[VAL_56]]
// CHECK:         %[[VAL_59:.*]] = load float, ptr %[[VAL_57]], align 4, !invariant.load
// CHECK:         %[[VAL_60:.*]] = fptrunc float %[[VAL_59]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id7:                    ; preds = %[[VAL_61:.*]]
// CHECK:         %[[VAL_62:.*]] = phi i32 [ 7000, %[[VAL_61]] ]
// CHECK:         %[[VAL_63:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_62]]
// CHECK:         %[[VAL_64:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_65:.*]], i32 0, i32 %[[VAL_63]]
// CHECK:         %[[VAL_66:.*]] = load float, ptr %[[VAL_64]], align 4, !invariant.load
// CHECK:         %[[VAL_67:.*]] = fptrunc float %[[VAL_66]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id8:                    ; preds = %[[VAL_68:.*]]
// CHECK:         %[[VAL_69:.*]] = phi i32 [ 8000, %[[VAL_68]] ]
// CHECK:         %[[VAL_70:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_69]]
// CHECK:         %[[VAL_71:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_72:.*]], i32 0, i32 %[[VAL_70]]
// CHECK:         %[[VAL_73:.*]] = load float, ptr %[[VAL_71]], align 4, !invariant.load
// CHECK:         %[[VAL_74:.*]] = fptrunc float %[[VAL_73]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id9:                    ; preds = %[[VAL_75:.*]]
// CHECK:         %[[VAL_76:.*]] = phi i32 [ 9000, %[[VAL_75]] ]
// CHECK:         %[[VAL_77:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_76]]
// CHECK:         %[[VAL_78:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_79:.*]], i32 0, i32 %[[VAL_77]]
// CHECK:         %[[VAL_80:.*]] = load float, ptr %[[VAL_78]], align 4, !invariant.load
// CHECK:         %[[VAL_81:.*]] = fptrunc float %[[VAL_80]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concat_index_from_operand_id10:                   ; preds = %[[VAL_82:.*]]
// CHECK:         %[[VAL_83:.*]] = phi i32 [ 10000, %[[VAL_82]] ]
// CHECK:         %[[VAL_84:.*]] = sub nsw i32 %[[VAL_5]], %[[VAL_83]]
// CHECK:         %[[VAL_85:.*]] = getelementptr inbounds [1000 x float], ptr %[[VAL_86:.*]], i32 0, i32 %[[VAL_84]]
// CHECK:         %[[VAL_87:.*]] = load float, ptr %[[VAL_85]], align 4, !invariant.load
// CHECK:         %[[VAL_88:.*]] = fptrunc float %[[VAL_87]] to half
// CHECK:         br label %[[VAL_9]]
// CHECK:       concatenate.pivot.5000.:                          ; preds = %[[VAL_7]]
// CHECK:         %[[VAL_89:.*]] = icmp ult i32 %[[VAL_5]], 5000
// CHECK:         br i1 %[[VAL_89]], label %[[VAL_90:.*]], label %[[VAL_91:.*]]
// CHECK:       concatenate.pivot.2000.:                          ; preds = %[[VAL_11]]
// CHECK:         %[[VAL_92:.*]] = icmp ult i32 %[[VAL_5]], 2000
// CHECK:         br i1 %[[VAL_92]], label %[[VAL_93:.*]], label %[[VAL_94:.*]]
// CHECK:       concatenate.pivot.1000.:                          ; preds = %[[VAL_90]]
// CHECK:         %[[VAL_95:.*]] = icmp ult i32 %[[VAL_5]], 1000
// CHECK:         br i1 %[[VAL_95]], label %[[VAL_12]], label %[[VAL_19]]
// CHECK:       concatenate.pivot.0.:                             ; preds = %[[VAL_93]]
// CHECK:         br label %[[VAL_96:.*]]
// CHECK:       concatenate.pivot.1000.1:                         ; preds = %[[VAL_93]]
// CHECK:         br label %[[VAL_97:.*]]
// CHECK:       concatenate.pivot.3000.:                          ; preds = %[[VAL_90]]
// CHECK:         %[[VAL_98:.*]] = icmp ult i32 %[[VAL_5]], 3000
// CHECK:         br i1 %[[VAL_98]], label %[[VAL_26]], label %[[VAL_99:.*]]
// CHECK:       concatenate.pivot.2000.2:                         ; preds = %[[VAL_94]]
// CHECK:         br label %[[VAL_100:.*]]
// CHECK:       concatenate.pivot.4000.:                          ; preds = %[[VAL_94]]
// CHECK:         %[[VAL_101:.*]] = icmp ult i32 %[[VAL_5]], 4000
// CHECK:         br i1 %[[VAL_101]], label %[[VAL_33]], label %[[VAL_40]]
// CHECK:       concatenate.pivot.3000.3:                         ; preds = %[[VAL_99]]
// CHECK:         br label %[[VAL_102:.*]]
// CHECK:       concatenate.pivot.4000.4:                         ; preds = %[[VAL_99]]
// CHECK:         br label %[[VAL_103:.*]]
// CHECK:       concatenate.pivot.8000.:                          ; preds = %[[VAL_11]]
// CHECK:         %[[VAL_104:.*]] = icmp ult i32 %[[VAL_5]], 8000
// CHECK:         br i1 %[[VAL_104]], label %[[VAL_105:.*]], label %[[VAL_106:.*]]
// CHECK:       concatenate.pivot.6000.:                          ; preds = %[[VAL_91]]
// CHECK:         %[[VAL_107:.*]] = icmp ult i32 %[[VAL_5]], 6000
// CHECK:         br i1 %[[VAL_107]], label %[[VAL_47]], label %[[VAL_108:.*]]
// CHECK:       concatenate.pivot.5000.5:                         ; preds = %[[VAL_105]]
// CHECK:         br label %[[VAL_109:.*]]
// CHECK:       concatenate.pivot.7000.:                          ; preds = %[[VAL_105]]
// CHECK:         %[[VAL_110:.*]] = icmp ult i32 %[[VAL_5]], 7000
// CHECK:         br i1 %[[VAL_110]], label %[[VAL_54]], label %[[VAL_61]]
// CHECK:       concatenate.pivot.6000.6:                         ; preds = %[[VAL_108]]
// CHECK:         br label %[[VAL_111:.*]]
// CHECK:       concatenate.pivot.7000.7:                         ; preds = %[[VAL_108]]
// CHECK:         br label %[[VAL_112:.*]]
// CHECK:       concatenate.pivot.9000.:                          ; preds = %[[VAL_91]]
// CHECK:         %[[VAL_113:.*]] = icmp ult i32 %[[VAL_5]], 9000
// CHECK:         br i1 %[[VAL_113]], label %[[VAL_68]], label %[[VAL_114:.*]]
// CHECK:       concatenate.pivot.8000.8:                         ; preds = %[[VAL_106]]
// CHECK:         br label %[[VAL_115:.*]]
// CHECK:       concatenate.pivot.10000.:                         ; preds = %[[VAL_106]]
// CHECK:         %[[VAL_116:.*]] = icmp ult i32 %[[VAL_5]], 10000
// CHECK:         br i1 %[[VAL_116]], label %[[VAL_75]], label %[[VAL_82]]
// CHECK:       concatenate.pivot.9000.9:                         ; preds = %[[VAL_114]]
// CHECK:         br label %[[VAL_117:.*]]
// CHECK:       concatenate.pivot.10000.10:                       ; preds = %[[VAL_114]]
// CHECK:         br label %[[VAL_118:.*]]
// CHECK:       out.1.merge:                                      ; preds = %[[VAL_118]], %[[VAL_117]], %[[VAL_115]], %[[VAL_112]], %[[VAL_111]], %[[VAL_109]], %[[VAL_103]], %[[VAL_102]], %[[VAL_100]], %[[VAL_97]], %[[VAL_96]]
// CHECK:         %[[VAL_119:.*]] = phi half [ %[[VAL_18]], %[[VAL_96]] ], [ %[[VAL_25]], %[[VAL_97]] ], [ %[[VAL_32]], %[[VAL_100]] ], [ %[[VAL_39]], %[[VAL_102]] ], [ %[[VAL_46]], %[[VAL_103]] ], [ %[[VAL_53]], %[[VAL_109]] ], [ %[[VAL_60]], %[[VAL_111]] ], [ %[[VAL_67]], %[[VAL_112]] ], [ %[[VAL_74]], %[[VAL_115]] ], [ %[[VAL_81]], %[[VAL_117]] ], [ %[[VAL_88]], %[[VAL_118]] ]
// CHECK:         %[[VAL_120:.*]] = getelementptr inbounds half, ptr %[[VAL_121:.*]], i32 %[[VAL_3]]
// CHECK:         store half %[[VAL_119]], ptr %[[VAL_120]], align 2
// CHECK:         br label %[[VAL_8]]

HloModule module, is_scheduled=true

%fused_computation (param_0.1: f32[1000], param_1.2: f32[1000], param_2.3: f32[1000], param_3.4: f32[1000], param_4.5: f32[1000], param_5.6: f32[1000], param_6.7: f32[1000], param_7.8: f32[1000], param_8.9: f32[1000], param_9.10: f32[1000], param_10.11: f32[1000]) -> f16[11000] {
  %param_10.11 = f32[1000]{0} parameter(10)
  %converted0.1 = f16[1000]{0} convert(f32[1000]{0} %param_10.11)
  %param_9.10 = f32[1000]{0} parameter(9)
  %converted1.1 = f16[1000]{0} convert(f32[1000]{0} %param_9.10)
  %param_8.9 = f32[1000]{0} parameter(8)
  %converted2.1 = f16[1000]{0} convert(f32[1000]{0} %param_8.9)
  %param_7.8 = f32[1000]{0} parameter(7)
  %converted3.1 = f16[1000]{0} convert(f32[1000]{0} %param_7.8)
  %param_6.7 = f32[1000]{0} parameter(6)
  %converted4.1 = f16[1000]{0} convert(f32[1000]{0} %param_6.7)
  %param_5.6 = f32[1000]{0} parameter(5)
  %converted5.1 = f16[1000]{0} convert(f32[1000]{0} %param_5.6)
  %param_4.5 = f32[1000]{0} parameter(4)
  %converted6.1 = f16[1000]{0} convert(f32[1000]{0} %param_4.5)
  %param_3.4 = f32[1000]{0} parameter(3)
  %converted7.1 = f16[1000]{0} convert(f32[1000]{0} %param_3.4)
  %param_2.3 = f32[1000]{0} parameter(2)
  %converted8.1 = f16[1000]{0} convert(f32[1000]{0} %param_2.3)
  %param_1.2 = f32[1000]{0} parameter(1)
  %converted9.1 = f16[1000]{0} convert(f32[1000]{0} %param_1.2)
  %param_0.1 = f32[1000]{0} parameter(0)
  %converted10.1 = f16[1000]{0} convert(f32[1000]{0} %param_0.1)
  ROOT %out.1 = f16[11000]{0} concatenate(f16[1000]{0} %converted0.1, f16[1000]{0} %converted1.1, f16[1000]{0} %converted2.1, f16[1000]{0} %converted3.1, f16[1000]{0} %converted4.1, /*index=5*/f16[1000]{0} %converted5.1, f16[1000]{0} %converted6.1, f16[1000]{0} %converted7.1, f16[1000]{0} %converted8.1, f16[1000]{0} %converted9.1, /*index=10*/f16[1000]{0} %converted10.1), dimensions={0}
}

ENTRY %computation (p0: f32[1000], p1: f32[1000], p2: f32[1000], p3: f32[1000], p4: f32[1000], p5: f32[1000], p6: f32[1000], p7: f32[1000], p8: f32[1000], p9: f32[1000], p10: f32[1000]) -> f16[11000] {
  %p10 = f32[1000]{0} parameter(10)
  %p9 = f32[1000]{0} parameter(9)
  %p8 = f32[1000]{0} parameter(8)
  %p7 = f32[1000]{0} parameter(7)
  %p6 = f32[1000]{0} parameter(6)
  %p5 = f32[1000]{0} parameter(5)
  %p4 = f32[1000]{0} parameter(4)
  %p3 = f32[1000]{0} parameter(3)
  %p2 = f32[1000]{0} parameter(2)
  %p1 = f32[1000]{0} parameter(1)
  %p0 = f32[1000]{0} parameter(0)
  ROOT %fusion = f16[11000]{0} fusion(f32[1000]{0} %p10, f32[1000]{0} %p9, f32[1000]{0} %p8, f32[1000]{0} %p7, f32[1000]{0} %p6, /*index=5*/f32[1000]{0} %p5, f32[1000]{0} %p4, f32[1000]{0} %p3, f32[1000]{0} %p2, f32[1000]{0} %p1, /*index=10*/f32[1000]{0} %p0), kind=kLoop, calls=%fused_computation
}

