# Copyright 2026 The OpenXLA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class GpuDeviceInfo:
  @property
  def device_vendor(self) -> str: ...
  @property
  def platform_version(self) -> str: ...
  @property
  def pci_bus_id(self) -> str: ...
  @property
  def name(self) -> str: ...
  @property
  def model_str(self) -> str: ...
  @property
  def threads_per_block_limit(self) -> int: ...
  @property
  def threads_per_warp(self) -> int: ...
  @property
  def shared_memory_per_block(self) -> int: ...
  @property
  def shared_memory_per_core(self) -> int: ...
  @property
  def threads_per_core_limit(self) -> int: ...
  @property
  def core_count(self) -> int: ...
  @property
  def fpus_per_core(self) -> int: ...
  @property
  def block_dim_limit_x(self) -> int: ...
  @property
  def block_dim_limit_y(self) -> int: ...
  @property
  def block_dim_limit_z(self) -> int: ...
  @property
  def memory_bandwidth(self) -> int: ...
  @property
  def l2_cache_size(self) -> int: ...
  @property
  def clock_rate_ghz(self) -> float: ...
  @property
  def device_memory_size(self) -> int: ...
  @property
  def shared_memory_per_block_optin(self) -> int: ...
  @property
  def registers_per_core_limit(self) -> int: ...
  @property
  def registers_per_block_limit(self) -> int: ...
  @property
  def driver_version(self) -> str: ...
  @property
  def kernel_mode_driver_version(self) -> str: ...
  @property
  def runtime_version(self) -> str: ...
  @property
  def compile_time_toolkit_version(self) -> str: ...
  @property
  def dnn_version(self) -> str: ...
  @property
  def cub_version(self) -> str: ...
  @property
  def numa_node(self) -> int: ...
  @property
  def thread_dim_limit_x(self) -> int: ...
  @property
  def thread_dim_limit_y(self) -> int: ...
  @property
  def thread_dim_limit_z(self) -> int: ...
  @property
  def device_address_bits(self) -> int: ...
  @property
  def pcie_bandwidth(self) -> int: ...
  @property
  def ecc_enabled(self) -> bool: ...
  @property
  def mem_clock_ghz(self) -> float: ...
  @property
  def reserved_shared_memory_per_block(self) -> int: ...
  @property
  def max_blocks_per_multiprocessor(self) -> int: ...
  @property
  def collective_memory_granularity(self) -> int: ...

class GpuTargetConfig:
  @property
  def gpu_device_info(self) -> GpuDeviceInfo: ...
  @property
  def platform_name(self) -> str: ...
  @property
  def device_description_str(self) -> str: ...
  @property
  def arch_name(self) -> str: ...
  @property
  def compute_capability(self) -> int: ...

def get_gpu_spec(device_kind: str) -> GpuTargetConfig: ...
