# Copyright 2026 The OpenXLA Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Fusion Explorer local visualization server.

This script is packaged into the self-contained Zipapp executable
generated by hlo_graph_dumper when --xla_dump_fusion_visualization
is enabled. It runs a local web server to host the interactive visualization
UI and serves HLO graphs from the embedded SQLite database.
"""

import http.server
import json
import os
import socket
import sqlite3
import sys
import tempfile
import time
import urllib.parse
import webbrowser
import zipfile


class FusionExplorerHandler(http.server.BaseHTTPRequestHandler):
  """Handler for Fusion Explorer APIs."""

  db_path = None

  def do_GET(self):  # pylint: disable=invalid-name
    """Handles GET requests."""
    parsed_url = urllib.parse.urlparse(self.path)

    if parsed_url.path in ("/", "/index.html"):
      with zipfile.ZipFile(sys.argv[0]) as z:
        html = z.read("viewer.html")
      self.send_response(200)
      self.send_header("Content-type", "text/html")
      self.end_headers()
      self.wfile.write(html)

    elif parsed_url.path == "/api/metadata":
      conn = sqlite3.connect(self.db_path)
      cursor = conn.cursor()

      title = "Fusion Explorer"
      try:
        cursor.execute("SELECT value FROM metadata WHERE key = 'title'")
        row = cursor.fetchone()
        if row:
          title = row[0]
      except sqlite3.OperationalError:
        pass

      cursor.execute(
          "SELECT id, label, to_highlight, graph_id FROM frames ORDER BY id"
      )
      rows = cursor.fetchall()
      conn.close()

      frames = [
          {"id": r[0], "label": r[1], "to_highlight": r[2], "graph_id": r[3]}
          for r in rows
      ]
      response = {"title": title, "frames": frames}

      self.send_response(200)
      self.send_header("Content-type", "application/json")
      self.end_headers()
      self.wfile.write(json.dumps(response).encode())

    elif parsed_url.path == "/api/graph":
      query = urllib.parse.parse_qs(parsed_url.query)
      frame_id = query.get("id", [None])[0]
      if not frame_id:
        self.send_error(400, "Missing id parameter")
        return

      conn = sqlite3.connect(self.db_path)
      cursor = conn.cursor()
      cursor.execute(
          "SELECT graphs.content FROM frames JOIN graphs ON frames.graph_id ="
          " graphs.id WHERE frames.id = ?",
          (frame_id,),
      )
      row = cursor.fetchone()
      conn.close()

      if not row:
        self.send_error(404, "Frame not found")
        return

      self.send_response(200)
      self.send_header("Content-type", "text/plain")
      self.send_header("Content-Encoding", "gzip")
      self.end_headers()
      self.wfile.write(row[0])

    else:
      self.send_error(404, "Not found")

  def log_message(self, fmt, *args):
    pass


def is_gui_browser(browser_controller) -> bool:
  """Returns True if the browser controller launches a GUI browser."""
  # Platform-specific default GUI controllers (Windows & macOS)
  if hasattr(webbrowser, "WindowsDefault") and isinstance(
      browser_controller, webbrowser.WindowsDefault
  ):
    return True
  if hasattr(webbrowser, "MacOSXOSAScript") and isinstance(
      browser_controller, webbrowser.MacOSXOSAScript
  ):
    return True

  # Background command wrappers (e.g. xdg-open, gio open) are GUI
  if isinstance(browser_controller, webbrowser.BackgroundBrowser):
    return True

  # Unix remote-control browsers (e.g. Chrome, Firefox have background=True)
  if isinstance(browser_controller, webbrowser.UnixBrowser):
    return getattr(browser_controller, "background", False)

  # Raw GenericBrowser (excluding BackgroundBrowser) runs in the foreground
  # and is used for terminal-based browsers (w3m, lynx, links)
  if isinstance(browser_controller, webbrowser.GenericBrowser):
    return False

  # Fallback check on custom/unrecognized controllers
  return getattr(browser_controller, "background", False)


def main():
  with tempfile.TemporaryDirectory() as temp_dir:
    db_path = os.path.join(temp_dir, "fusions.db")
    start_time = time.time()
    try:
      with zipfile.ZipFile(sys.argv[0]) as z:
        with open(db_path, "wb") as f:
          f.write(z.read("fusions.db"))
      elapsed = time.time() - start_time
      print(f"Unpacked database in {elapsed:.2f}s")
    except Exception as e:  # pylint: disable=broad-exception-caught
      print(f"Error extracting database: {e}")
      sys.exit(1)

    try:
      host = socket.getfqdn()
    except Exception:  # pylint: disable=broad-exception-caught
      host = "localhost"

    FusionExplorerHandler.db_path = db_path
    server = http.server.HTTPServer(("0.0.0.0", 0), FusionExplorerHandler)
    port = server.server_address[1]

    url = f"http://{host}:{port}"
    print(f"Starting the server at {url}")

    browser = None
    try:
      browser = webbrowser.get()
    except webbrowser.Error:
      pass

    if browser is not None and is_gui_browser(browser):
      browser_name = getattr(browser, "name", "default")
      print(f"Opening in {browser_name}")
      try:
        browser.open(url)
      except Exception as e:  # pylint: disable=broad-exception-caught
        print(f"Failed to open browser: {e}")

    try:
      server.serve_forever()
    except KeyboardInterrupt:
      pass
    print("\nStopped and cleaned up.")


if __name__ == "__main__":
  main()
