// TODO: license?

#ifndef XLA_SERVICE_EXPERIMENTAL_SHARDING_STRATEGY_SOLVER_H_
#define XLA_SERVICE_EXPERIMENTAL_SHARDING_STRATEGY_SOLVER_H_


class ShardingStrategySolver;


#endif // XLA_SERVICE_EXPERIMENTAL_SHARDING_STRATEGY_SOLVER_H_