// TODO: license?

#ifndef XLA_SERVICE_EXPERIMENTAL_STRATEGY_SOLVER_H_
#define XLA_SERVICE_EXPERIMENTAL_STRATEGY_SOLVER_H_


class StrategySolver


#endif // XLA_SERVICE_EXPERIMENTAL_STRATEGY_SOLVER_H_